# Generated by Django 5.2 on 2025-05-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
