# Generated by Django 5.2 on 2025-05-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abray', '0002_remove_course_end_date_remove_course_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_limit',
        ),
    ]
